"""Export palettes as SkyrimBridge weather-workshop presets.

The SkyrimBridge plugin live-edits weather records in game and keys its
presets by EditorID under Data/SKSE/Plugins/SkyrimBridge/WeatherPresets.
This exporter emits the same INI dialect for every archetype, so a weather
authored by the model here can be tuned live in game, and a tuned preset can
be compared back against the model.

Only model-owned sections are written ([Colors], [Fog], [WeatherData],
[DirectionalAmbient]): the editor overlays presets onto the captured live
weather, so omitted sections (clouds, image spaces, volumetric lighting)
keep their in-game values.
"""

from __future__ import annotations

from pathlib import Path

from ..esp.weather import ColorType, TimeOfDay, WeatherView
from .archetypes import edid_of

# Names must match the plugin's parser exactly.
COLOR_TYPE_NAMES = {
    ColorType.SKY_UPPER: "Sky Upper",
    ColorType.FOG_NEAR: "Fog Near",
    ColorType.CLOUD_LAYER_LOWER: "Unknown",
    ColorType.AMBIENT: "Ambient",
    ColorType.SUNLIGHT: "Sunlight",
    ColorType.SUN: "Sun",
    ColorType.STARS: "Stars",
    ColorType.SKY_LOWER: "Sky Lower",
    ColorType.HORIZON: "Horizon",
    ColorType.EFFECT_LIGHTING: "Effect Lighting",
    ColorType.CLOUD_LOD_DIFFUSE: "Cloud LOD Diffuse",
    ColorType.CLOUD_LOD_AMBIENT: "Cloud LOD Ambient",
    ColorType.FOG_FAR: "Fog Far",
    ColorType.SKY_STATICS: "Sky Statics",
    ColorType.WATER_MULTIPLIER: "Water Multiplier",
    ColorType.SUN_GLARE: "Sun Glare",
    ColorType.MOON_GLARE: "Moon Glare",
}

TOD_NAMES = {
    TimeOfDay.SUNRISE: "Sunrise",
    TimeOfDay.DAY: "Day",
    TimeOfDay.SUNSET: "Sunset",
    TimeOfDay.NIGHT: "Night",
}

_FIRST_FORM_ID = 0x01000800  # matches the esp writer's assignment order


def _n(v: int) -> str:
    """Byte channel to the editor's normalized float."""
    return f"{v / 255.0:.6g}"


def _ambient_row(view: WeatherView, tod: TimeOfDay, scale: float) -> str:
    a = view.color(ColorType.AMBIENT, tod)
    r = min(255, int(a.r * scale))
    g = min(255, int(a.g * scale))
    b = min(255, int(a.b * scale))
    return f"{_n(r)}, {_n(g)}, {_n(b)}, 1"


def _write_preset(view: WeatherView, edid: str, form_id: int, path: Path) -> None:
    lines: list[str] = []
    w = lines.append

    w("; SkyrimBridge Weather Preset")
    w(f"; Generated by elder-weathers from the '{view.edid}' archetype model")
    w("")
    w("[Identity]")
    w(f"FormID = 0x{form_id:x}")
    w(f"EditorID = {edid}")
    w("")
    w("[Colors]")
    for ct in ColorType:
        for tod in TimeOfDay:
            c = view.color(ct, tod)
            w(f"{COLOR_TYPE_NAMES[ct]}_{TOD_NAMES[tod]} = "
              f"{_n(c.r)}, {_n(c.g)}, {_n(c.b)}, {_n(c.a)}")
    w("")
    w("[Fog]")
    fog = view.fog
    w(f"DayNear = {fog.day_near:.6g}")
    w(f"DayFar = {fog.day_far:.6g}")
    w(f"NightNear = {fog.night_near:.6g}")
    w(f"NightFar = {fog.night_far:.6g}")
    w(f"DayPower = {fog.day_pow:.6g}")
    w(f"NightPower = {fog.night_pow:.6g}")
    w(f"DayMax = {fog.day_max:.6g}")
    w(f"NightMax = {fog.night_max:.6g}")
    w("")
    w("[WeatherData]")
    w(f"WindSpeed = {_n(view.data[0])}")
    w(f"TransDelta = {_n(view.data[3])}")
    w(f"SunGlare = {_n(view.data[4])}")
    w(f"Flags = {view.flags}")
    w(f"LightningColor = {_n(view.data[12])}, {_n(view.data[13])}, {_n(view.data[14])}")
    w("")
    w("[DirectionalAmbient]")
    for tod in TimeOfDay:
        name = TOD_NAMES[tod]
        w(f"XMax_{name} = {_ambient_row(view, tod, 1.0)}")
        w(f"XMin_{name} = {_ambient_row(view, tod, 1.0)}")
        w(f"YMax_{name} = {_ambient_row(view, tod, 1.0)}")
        w(f"YMin_{name} = {_ambient_row(view, tod, 1.0)}")
        w(f"ZMax_{name} = {_ambient_row(view, tod, 1.25)}")
        w(f"ZMin_{name} = {_ambient_row(view, tod, 0.6)}")
        w(f"Specular_{name} = {_ambient_row(view, tod, 0.5)}")
        w(f"FresnelPower_{name} = 1")
    w("")

    path.write_text("\n".join(lines), encoding="utf-8")


def export_presets(palettes: dict[str, WeatherView], out_dir: Path) -> list[Path]:
    """Write one workshop preset per archetype; returns the written paths."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for i, name in enumerate(sorted(palettes)):
        edid = edid_of(name)
        path = out_dir / f"{edid}.ini"
        _write_preset(palettes[name], edid, _FIRST_FORM_ID + i, path)
        written.append(path)
    return written
